import {
  Send,
  ArrowLeft,
  Loader2,
  MessageSquare,
  User,
  Bot,
  Sparkles,
  Code,
  Database,
  Laptop,
  Smartphone,
  Gamepad2,
  Globe,
  Pencil,
  Edit,
  RefreshCw,
  Trash,
  Plus,
  Minus,
  X,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Menu,
  Search,
  Filter,
  type Icon as LucideIcon,
} from "lucide-react";

export type Icon = typeof LucideIcon;

export const Icons = {
  logo: MessageSquare,
  send: Send,
  spinner: Loader2,
  arrowLeft: ArrowLeft,
  user: User,
  bot: Bot,
  sparkles: Sparkles,
  code: Code,
  database: Database,
  laptop: Laptop,
  smartphone: Smartphone,
  game: Gamepad2,
  globe: Globe,
  pencil: Pencil,
  edit: Edit,
  refresh: RefreshCw,
  trash: Trash,
  plus: Plus,
  minus: Minus,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  search: Search,
  filter: Filter
};